# Generated by Django 3.1.3 on 2021-09-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
