# Generated by Django 3.1.3 on 2021-09-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_portal', '0002_question_modify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='modify_date',
        ),
    ]
