# Generated by Django 3.1.3 on 2021-09-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='thumbnail',
            field=models.CharField(default='C:\\projects\\mysite\\static\\네이버_로고.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
