# Generated by Django 3.1.3 on 2021-09-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_question_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
