# Generated by Django 3.1.3 on 2021-09-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_auto_20210907_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
