# Generated by Django 3.1.3 on 2021-09-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0016_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
